"""empty message

Revision ID: 4f8a59547b5e
Revises: a7df4de4f167
Create Date: 2022-05-02 19:28:32.531990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8a59547b5e'
down_revision = 'a7df4de4f167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('location', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'location')
    # ### end Alembic commands ###
