"""empty message

Revision ID: 6ebd45991331
Revises: 4f8a59547b5e
Create Date: 2022-05-03 13:17:30.661176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebd45991331'
down_revision = '4f8a59547b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('education_major', sa.String(length=50), nullable=True))
    op.add_column('user_account', sa.Column('education_institution', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'education_institution')
    op.drop_column('user_account', 'education_major')
    # ### end Alembic commands ###
